version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - ferserc1
  ignore:
  - dependency-name: bg2e-js
    versions:
    - ">= 1.4.a, < 1.5"
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.13.1
    - 7.13.14
    - 7.13.16
    - 7.13.8
  - dependency-name: nightwatch
    versions:
    - 1.6.1
    - 1.6.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.0
    - 7.13.10
    - 7.13.5
  - dependency-name: chromedriver
    versions:
    - 89.0.0
  - dependency-name: jquery
    versions:
    - 3.6.0
